
export const passwordResetConfirmTypes = {
    PASSWORDRESSETCONFIRM_REQUEST: 'PASSWORDRESSETCONFIRM_REQUEST',
    PASSWORDRESSETCONFIRM_SUCCESS: 'PASSWORDRESSETCONFIRM_SUCCESS',
    PASSWORDRESSETCONFIRM_FAIL: 'PASSWORDRESSETCONFIRM_FAIL',
}